//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anagramimation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anagramimation.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amusing
        ///angry
        ///athletic
        ///attractive
        ///beautiful
        ///boring
        ///brave
        ///careful
        ///careless
        ///charming
        ///clever
        ///confident
        ///crafty
        ///crazy
        ///creative
        ///cruel
        ///cute
        ///dangerous
        ///dependable
        ///easygoing
        ///energetic
        ///exciting
        ///famous
        ///forgetful
        ///friendly
        ///good-looking
        ///graceful
        ///happy
        ///helpful
        ///horrible
        ///humble
        ///humorous
        ///inconsiderate
        ///interesting
        ///likable
        ///lucky
        ///middle class
        ///old
        ///outgoing
        ///popular
        ///practical
        ///responsible
        ///rich
        ///romantic
        ///sad
        ///selfish
        ///stingy
        ///successful
        ///talkative
        ///touchy
        ///ugly
        ///unlucky
        ///wealthy
        ///young.
        /// </summary>
        public static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aback
        ///abacus
        ///abalone
        ///abandon
        ///abase
        ///abash
        ///abate
        ///abater
        ///abbas
        ///abbe
        ///abbey
        ///abbot
        ///abbreviate
        ///abc
        ///abdicate
        ///abdomen
        ///abdominal
        ///abduct
        ///abed
        ///aberrant
        ///aberrate
        ///abet
        ///abetted
        ///abetting
        ///abeyance
        ///abeyant
        ///abhorred
        ///abhorrent
        ///abide
        ///abject
        ///ablate
        ///ablaze
        ///able
        ///ablution
        ///abnormal
        ///aboard
        ///abode
        ///abolish
        ///abolition
        ///abominable
        ///abominate
        ///aboriginal
        ///aborigine
        ///aborning
        ///abort
        ///abound
        ///about
        ///above
        ///aboveboard
        ///aboveground
        ///abovementioned
        ///abrade
        ///abrasion
        ///abrasive
        ///abreact
        ///abreast
        ///abridge
        ///abridgment
        ///abroad
        ///abrogate
        ///abrupt
        ///abscess
        ///abscissa
        ///abscissa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AllWords {
            get {
                return ResourceManager.GetString("AllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aardvark
        ///Alligator
        ///Alpaca
        ///Anaconda
        ///Ant
        ///Antelope
        ///Ape
        ///Aphid
        ///Armadillo
        ///Asp
        ///Ass
        ///Baboon
        ///Badger
        ///Barracuda
        ///Bass
        ///Bat
        ///Bear
        ///Beaver
        ///Bedbug
        ///Bee
        ///Beetle
        ///Bird
        ///Bison
        ///Bobcat
        ///Buffalo
        ///Butterfly
        ///Buzzard
        ///Camel
        ///Caribou
        ///Carp
        ///Cat
        ///Caterpillar
        ///Catfish
        ///Cheetah
        ///Chicken
        ///Chimpanzee
        ///Chipmunk
        ///Cobra
        ///Cod
        ///Condor
        ///Cougar
        ///Cow
        ///Coyote
        ///Crab
        ///Crane
        ///Cricket
        ///Crocodile
        ///Crow
        ///Cuckoo
        ///Deer
        ///Dinosaur
        ///Dog
        ///Dolphin
        ///Donkey
        ///Dove
        ///Dragonfly
        ///Duck
        ///Eagle
        ///Eel
        ///Elephant
        ///Emu
        ///Falcon
        ///Ferret
        ///Finch
        ///Fish
        ///Flamingo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
    }
}
